# docker-compose.prod.yml
version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: travel-backend
    restart: always
    env_file: .env.prod
#    environment:
 #     - GROQ_API_KEY=${GROQ_API_KEY}
  #    - GEMINI_API_KEY=${GEMINI_API_KEY}
   #   - LLM_PROVIDER=${LLM_PROVIDER:-groq}
    #  - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost}
     # - DEBUG=false
    networks:
      - travel-net
    expose:
      - "8000"
    security_opt:
      - no-new-privileges:true
    read_only: true
    volumes:
      - /tmp
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: travel-frontend
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    restart: always
    environment:
      - BACKEND_URL=http://backend:8000
    networks:
      - travel-net
    expose:
      - "8501"
    security_opt:
      - no-new-privileges:true
    depends_on:
      - backend
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M

  nginx:
    image: nginx:alpine
    container_name: travel-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - travel-net
    depends_on:
      - backend
      - frontend
    security_opt:
      - no-new-privileges:true

networks:
  travel-net:
    driver: bridge
